name: Linux CI Tests

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: docker://espressif/idf:v4.3
    - uses: actions/checkout@v2
    - name: Style Check
      run: .github/scripts/code_style.sh check
    - name: Submodules Init
      uses: snickerbockers/submodules-init@v4
    - name: Configure
      run: .github/scripts/install_software.sh
    # - name: Check-in Tests
    #   run: sudo bash -c ".github/scripts/ci_tests.sh -st -nxp -pc"
    - name: Check-in Tests
      run: sudo bash -c ".github/scripts/ci_tests.sh -nxp -pc"
    - name: Build Esp32 Samples
      run: docker run -v "${PWD}:/iot-middleware-freertos-samples" -w /iot-middleware-freertos-samples espressif/idf:v4.3 .github/scripts/ci_tests.sh -esp
